# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keshavan/graphics/FighterJet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keshavan/graphics/FighterJet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keshavan/graphics/FighterJet/CMakeFiles /home/keshavan/graphics/FighterJet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keshavan/graphics/FighterJet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FighterJet

# Build rule for target.
FighterJet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FighterJet
.PHONY : FighterJet

# fast build rule for target.
FighterJet/fast:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/build
.PHONY : FighterJet/fast

src/ball.o: src/ball.cpp.o

.PHONY : src/ball.o

# target to build an object file
src/ball.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/ball.cpp.o
.PHONY : src/ball.cpp.o

src/ball.i: src/ball.cpp.i

.PHONY : src/ball.i

# target to preprocess a source file
src/ball.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/ball.cpp.i
.PHONY : src/ball.cpp.i

src/ball.s: src/ball.cpp.s

.PHONY : src/ball.s

# target to generate assembly for a file
src/ball.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/ball.cpp.s
.PHONY : src/ball.cpp.s

src/bomb.o: src/bomb.cpp.o

.PHONY : src/bomb.o

# target to build an object file
src/bomb.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/bomb.cpp.o
.PHONY : src/bomb.cpp.o

src/bomb.i: src/bomb.cpp.i

.PHONY : src/bomb.i

# target to preprocess a source file
src/bomb.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/bomb.cpp.i
.PHONY : src/bomb.cpp.i

src/bomb.s: src/bomb.cpp.s

.PHONY : src/bomb.s

# target to generate assembly for a file
src/bomb.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/bomb.cpp.s
.PHONY : src/bomb.cpp.s

src/color.o: src/color.cpp.o

.PHONY : src/color.o

# target to build an object file
src/color.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/color.cpp.o
.PHONY : src/color.cpp.o

src/color.i: src/color.cpp.i

.PHONY : src/color.i

# target to preprocess a source file
src/color.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/color.cpp.i
.PHONY : src/color.cpp.i

src/color.s: src/color.cpp.s

.PHONY : src/color.s

# target to generate assembly for a file
src/color.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/color.cpp.s
.PHONY : src/color.cpp.s

src/compass.o: src/compass.cpp.o

.PHONY : src/compass.o

# target to build an object file
src/compass.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/compass.cpp.o
.PHONY : src/compass.cpp.o

src/compass.i: src/compass.cpp.i

.PHONY : src/compass.i

# target to preprocess a source file
src/compass.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/compass.cpp.i
.PHONY : src/compass.cpp.i

src/compass.s: src/compass.cpp.s

.PHONY : src/compass.s

# target to generate assembly for a file
src/compass.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/compass.cpp.s
.PHONY : src/compass.cpp.s

src/enemy.o: src/enemy.cpp.o

.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i

.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s

.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/fuel.o: src/fuel.cpp.o

.PHONY : src/fuel.o

# target to build an object file
src/fuel.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/fuel.cpp.o
.PHONY : src/fuel.cpp.o

src/fuel.i: src/fuel.cpp.i

.PHONY : src/fuel.i

# target to preprocess a source file
src/fuel.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/fuel.cpp.i
.PHONY : src/fuel.cpp.i

src/fuel.s: src/fuel.cpp.s

.PHONY : src/fuel.s

# target to generate assembly for a file
src/fuel.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/fuel.cpp.s
.PHONY : src/fuel.cpp.s

src/fuelup.o: src/fuelup.cpp.o

.PHONY : src/fuelup.o

# target to build an object file
src/fuelup.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/fuelup.cpp.o
.PHONY : src/fuelup.cpp.o

src/fuelup.i: src/fuelup.cpp.i

.PHONY : src/fuelup.i

# target to preprocess a source file
src/fuelup.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/fuelup.cpp.i
.PHONY : src/fuelup.cpp.i

src/fuelup.s: src/fuelup.cpp.s

.PHONY : src/fuelup.s

# target to generate assembly for a file
src/fuelup.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/fuelup.cpp.s
.PHONY : src/fuelup.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/island.o: src/island.cpp.o

.PHONY : src/island.o

# target to build an object file
src/island.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/island.cpp.o
.PHONY : src/island.cpp.o

src/island.i: src/island.cpp.i

.PHONY : src/island.i

# target to preprocess a source file
src/island.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/island.cpp.i
.PHONY : src/island.cpp.i

src/island.s: src/island.cpp.s

.PHONY : src/island.s

# target to generate assembly for a file
src/island.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/island.cpp.s
.PHONY : src/island.cpp.s

src/jet.o: src/jet.cpp.o

.PHONY : src/jet.o

# target to build an object file
src/jet.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/jet.cpp.o
.PHONY : src/jet.cpp.o

src/jet.i: src/jet.cpp.i

.PHONY : src/jet.i

# target to preprocess a source file
src/jet.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/jet.cpp.i
.PHONY : src/jet.cpp.i

src/jet.s: src/jet.cpp.s

.PHONY : src/jet.s

# target to generate assembly for a file
src/jet.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/jet.cpp.s
.PHONY : src/jet.cpp.s

src/lifeup.o: src/lifeup.cpp.o

.PHONY : src/lifeup.o

# target to build an object file
src/lifeup.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/lifeup.cpp.o
.PHONY : src/lifeup.cpp.o

src/lifeup.i: src/lifeup.cpp.i

.PHONY : src/lifeup.i

# target to preprocess a source file
src/lifeup.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/lifeup.cpp.i
.PHONY : src/lifeup.cpp.i

src/lifeup.s: src/lifeup.cpp.s

.PHONY : src/lifeup.s

# target to generate assembly for a file
src/lifeup.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/lifeup.cpp.s
.PHONY : src/lifeup.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/missile.o: src/missile.cpp.o

.PHONY : src/missile.o

# target to build an object file
src/missile.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/missile.cpp.o
.PHONY : src/missile.cpp.o

src/missile.i: src/missile.cpp.i

.PHONY : src/missile.i

# target to preprocess a source file
src/missile.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/missile.cpp.i
.PHONY : src/missile.cpp.i

src/missile.s: src/missile.cpp.s

.PHONY : src/missile.s

# target to generate assembly for a file
src/missile.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/missile.cpp.s
.PHONY : src/missile.cpp.s

src/nonedit.o: src/nonedit.cpp.o

.PHONY : src/nonedit.o

# target to build an object file
src/nonedit.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/nonedit.cpp.o
.PHONY : src/nonedit.cpp.o

src/nonedit.i: src/nonedit.cpp.i

.PHONY : src/nonedit.i

# target to preprocess a source file
src/nonedit.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/nonedit.cpp.i
.PHONY : src/nonedit.cpp.i

src/nonedit.s: src/nonedit.cpp.s

.PHONY : src/nonedit.s

# target to generate assembly for a file
src/nonedit.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/nonedit.cpp.s
.PHONY : src/nonedit.cpp.s

src/other_handlers.o: src/other_handlers.cpp.o

.PHONY : src/other_handlers.o

# target to build an object file
src/other_handlers.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/other_handlers.cpp.o
.PHONY : src/other_handlers.cpp.o

src/other_handlers.i: src/other_handlers.cpp.i

.PHONY : src/other_handlers.i

# target to preprocess a source file
src/other_handlers.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/other_handlers.cpp.i
.PHONY : src/other_handlers.cpp.i

src/other_handlers.s: src/other_handlers.cpp.s

.PHONY : src/other_handlers.s

# target to generate assembly for a file
src/other_handlers.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/other_handlers.cpp.s
.PHONY : src/other_handlers.cpp.s

src/parachutes.o: src/parachutes.cpp.o

.PHONY : src/parachutes.o

# target to build an object file
src/parachutes.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/parachutes.cpp.o
.PHONY : src/parachutes.cpp.o

src/parachutes.i: src/parachutes.cpp.i

.PHONY : src/parachutes.i

# target to preprocess a source file
src/parachutes.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/parachutes.cpp.i
.PHONY : src/parachutes.cpp.i

src/parachutes.s: src/parachutes.cpp.s

.PHONY : src/parachutes.s

# target to generate assembly for a file
src/parachutes.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/parachutes.cpp.s
.PHONY : src/parachutes.cpp.s

src/pointer.o: src/pointer.cpp.o

.PHONY : src/pointer.o

# target to build an object file
src/pointer.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/pointer.cpp.o
.PHONY : src/pointer.cpp.o

src/pointer.i: src/pointer.cpp.i

.PHONY : src/pointer.i

# target to preprocess a source file
src/pointer.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/pointer.cpp.i
.PHONY : src/pointer.cpp.i

src/pointer.s: src/pointer.cpp.s

.PHONY : src/pointer.s

# target to generate assembly for a file
src/pointer.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/pointer.cpp.s
.PHONY : src/pointer.cpp.s

src/score.o: src/score.cpp.o

.PHONY : src/score.o

# target to build an object file
src/score.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/score.cpp.o
.PHONY : src/score.cpp.o

src/score.i: src/score.cpp.i

.PHONY : src/score.i

# target to preprocess a source file
src/score.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/score.cpp.i
.PHONY : src/score.cpp.i

src/score.s: src/score.cpp.s

.PHONY : src/score.s

# target to generate assembly for a file
src/score.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/score.cpp.s
.PHONY : src/score.cpp.s

src/smoke.o: src/smoke.cpp.o

.PHONY : src/smoke.o

# target to build an object file
src/smoke.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/smoke.cpp.o
.PHONY : src/smoke.cpp.o

src/smoke.i: src/smoke.cpp.i

.PHONY : src/smoke.i

# target to preprocess a source file
src/smoke.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/smoke.cpp.i
.PHONY : src/smoke.cpp.i

src/smoke.s: src/smoke.cpp.s

.PHONY : src/smoke.s

# target to generate assembly for a file
src/smoke.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/smoke.cpp.s
.PHONY : src/smoke.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/tower.o: src/tower.cpp.o

.PHONY : src/tower.o

# target to build an object file
src/tower.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/tower.cpp.o
.PHONY : src/tower.cpp.o

src/tower.i: src/tower.cpp.i

.PHONY : src/tower.i

# target to preprocess a source file
src/tower.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/tower.cpp.i
.PHONY : src/tower.cpp.i

src/tower.s: src/tower.cpp.s

.PHONY : src/tower.s

# target to generate assembly for a file
src/tower.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/tower.cpp.s
.PHONY : src/tower.cpp.s

src/volcano.o: src/volcano.cpp.o

.PHONY : src/volcano.o

# target to build an object file
src/volcano.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/volcano.cpp.o
.PHONY : src/volcano.cpp.o

src/volcano.i: src/volcano.cpp.i

.PHONY : src/volcano.i

# target to preprocess a source file
src/volcano.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/volcano.cpp.i
.PHONY : src/volcano.cpp.i

src/volcano.s: src/volcano.cpp.s

.PHONY : src/volcano.s

# target to generate assembly for a file
src/volcano.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/volcano.cpp.s
.PHONY : src/volcano.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/FighterJet.dir/build.make CMakeFiles/FighterJet.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... FighterJet"
	@echo "... edit_cache"
	@echo "... src/ball.o"
	@echo "... src/ball.i"
	@echo "... src/ball.s"
	@echo "... src/bomb.o"
	@echo "... src/bomb.i"
	@echo "... src/bomb.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/compass.o"
	@echo "... src/compass.i"
	@echo "... src/compass.s"
	@echo "... src/enemy.o"
	@echo "... src/enemy.i"
	@echo "... src/enemy.s"
	@echo "... src/fuel.o"
	@echo "... src/fuel.i"
	@echo "... src/fuel.s"
	@echo "... src/fuelup.o"
	@echo "... src/fuelup.i"
	@echo "... src/fuelup.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/island.o"
	@echo "... src/island.i"
	@echo "... src/island.s"
	@echo "... src/jet.o"
	@echo "... src/jet.i"
	@echo "... src/jet.s"
	@echo "... src/lifeup.o"
	@echo "... src/lifeup.i"
	@echo "... src/lifeup.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/missile.o"
	@echo "... src/missile.i"
	@echo "... src/missile.s"
	@echo "... src/nonedit.o"
	@echo "... src/nonedit.i"
	@echo "... src/nonedit.s"
	@echo "... src/other_handlers.o"
	@echo "... src/other_handlers.i"
	@echo "... src/other_handlers.s"
	@echo "... src/parachutes.o"
	@echo "... src/parachutes.i"
	@echo "... src/parachutes.s"
	@echo "... src/pointer.o"
	@echo "... src/pointer.i"
	@echo "... src/pointer.s"
	@echo "... src/score.o"
	@echo "... src/score.i"
	@echo "... src/score.s"
	@echo "... src/smoke.o"
	@echo "... src/smoke.i"
	@echo "... src/smoke.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/tower.o"
	@echo "... src/tower.i"
	@echo "... src/tower.s"
	@echo "... src/volcano.o"
	@echo "... src/volcano.i"
	@echo "... src/volcano.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

